### PR TITLE
README cleanup, make MoveIt installation optional

### PR DESCRIPTION
**Pull request by destogl**

### CODE REVIEW

**Comment by AndyZe** [comment]
Let's use this PR to do a bunch of README cleanup. Mostly small grammar things. I'll push some changes by the end of the day   :+1:

**Comment by destogl** [comment]
This addresses #74 by splitting .repos files.

**Review by AndyZe — APPROVED** [review]
I tested the new separation of `.repos` and nit-picked a bunch of grammar. Looks good to me  :+1:

Let's try not to change the README too much after this gets approved/merged.

**Review by nbbrooks — APPROVED** [review]
lgtm

**Pull request merged**
