### PR TITLE
Use GitHub Actions instead of Travis

### PR DESCRIPTION
**Pull request by destogl**
Add CI configuration files. Let's see how this works out...

- [x] Adjust lint formating

first part of #52

### CODE REVIEW

**Comment by destogl** [comment]
@livanov93 can you enable Github actions? Usually, they start automatically when there are configuration files.

**Comment by livanov93** [comment]
> 
> 
> @livanov93 can you enable Github actions? Usually, they start automatically when there are configuration files.

But the configuration files aren't there yet. They are on your fork of the repo.

**Comment by destogl** [comment]
> > @livanov93 can you enable Github actions? Usually, they start automatically when there are configuration files.
> 
> But the configuration files aren't there yet. They are on your fork of the repo.

Oh, you are right, sorry... Can we then merge this on another branch in this repo, so I can test there and then push to `develop` when CI is working? Can you please push it in this repo!

**Comment by livanov93** [comment]
> > > @livanov93 can you enable Github actions? Usually, they start automatically when there are configuration files.
> 
> > 
> 
> > But the configuration files aren't there yet. They are on your fork of the repo.
> 
> 
> 
> Oh, you are right, sorry... Can we then merge this on another branch in this repo, so I can test there and then push to `develop` when CI is working? Can you please push it in this repo!

I'll push this PR into another branch so you can continue with your work there.

**Pull request merged**
