### PR TITLE
Add universal robots e-series decription and configuration files

### PR DESCRIPTION
**Pull request by livanov93**
Prepare UR e-series robots packages for  ROS2

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Could I suggest to port the packages in this branch: [ros-industrial/universal_robot@melodic-devel-staging](https://github.com/ros-industrial/universal_robot/tree/melodic-devel-staging).

Let's not perpetuate the `ur_e_*` packages, except for the MoveIt packages.

**Comment by gavanderhoorn** [comment]
I'm also not entirely sure I'd put the MoveIt configurations in the same repository, tbh.

**Comment by livanov93** [comment]
I agree about having one ur_description package. 
Regarding moveit packages, for first trajectory demonstration I will have these within the driver repository. They can and will be deleted afterwards, to make the package look more like [ROS1 version](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver). This should follow after universal_robots package migration towards `ament_cmake`.

**Comment by AndyZe** [comment]
> Regarding moveit packages, for first trajectory demonstration I will have these within the driver repository. They can and will be deleted afterwards

Let's not be so certain yet. There are a lot of groups involved and there will probably be some discussion about it

**Comment by livanov93** [comment]
> Let's not be so certain yet. There are a lot of groups involved and there will probably be some discussion about it

Then we won't rush with these  package organization decisions.
Moving the robot on ROS2 is the top priority.

**Comment by AndyZe** [comment]
It probably would have been best to start from the `develop` branch, since what you're adding here doesn't depend on the hardware_interface PR (as far as I can tell).

**Comment by livanov93** [comment]
I've set it to develop as it should be. You're right, this doesn't depend on the [HW PR](https://github.com/PickNikRobotics/Universal_Robots_ROS2_Driver/pull/8).

**Comment by livanov93** [comment]
Added in #14

**Pull request closed without merging**
